apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-files
          mountPath: /usr/share/nginx/html  # Nginx sirve archivos desde aquí
      volumes:
      - name: web-files
        hostPath:
          path: /tmp/sitio-web  # ¡Carpeta TEMPORAL en Minikube!
          type: DirectoryOrCreate  # Si no existe, se crea

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80